export const countries = [
  {label: "United States of America", value: "USA", available: true},
  {label: "Canada", value: "CA", available: true},
  {label: "Afghanistan", value: "AF", available: true},
  {label: "Åland Islands", value: "AX", available: true},
  {label: "Albania", value: "AL", available: true},
  {label: "Algeria", value: "DZ", available: true},
  {label: "American Samoa", value: "AS", available: true},
  {label: "Andorra", value: "AD", available: true},
  {label: "Angola", value: "AO", available: true},
  {label: "Anguilla", value: "AI", available: true},
  {label: "Antarctica", value: "AQ", available: true},
  {label: "Antigua and Barbuda", value: "AG", available: true},
  {label: "Argentina", value: "AR", available: true},
  {label: "Armenia", value: "AM", available: true},
  {label: "Aruba", value: "AW", available: true},
  {label: "Australia", value: "AU", available: true},
  {label: "Austria", value: "AT", available: true},
  {label: "Azerbaijan", value: "AZ", available: true},
  {label: "Bahamas", value: "BS", available: true},
  {label: "Bahrain", value: "BH", available: true},
  {label: "Bangladesh", value: "BD", available: true},
  {label: "Barbados", value: "BB", available: true},
  {label: "Belarus", value: "BY", available: true},
  {label: "Belgium", value: "BE", available: true},
  {label: "Belize", value: "BZ", available: true},
  {label: "Benin", value: "BJ", available: true},
  {label: "Bermuda", value: "BM", available: true},
  {label: "Bhutan", value: "BT", available: true},
  {label: "Bolivia", value: "BO", available: true},
  {label: "Bosnia and Herzegovina", value: "BA", available: true},
  {label: "Botswana", value: "BW", available: true},
  {label: "Bouvet Island", value: "BV", available: true},
  {label: "Brazil", value: "BR", available: true},
  {label: "British Indian Ocean Territory", value: "IO", available: true},
  {label: "Brunei Darussalam", value: "BN", available: true},
  {label: "Bulgaria", value: "BG", available: true},
  {label: "Burkina Faso", value: "BF", available: true},
  {label: "Burundi", value: "BI", available: true},
  {label: "Cambodia", value: "KH", available: true},
  {label: "Cameroon", value: "CM", available: true},
  {label: "Cape Verde", value: "CV", available: true},
  {label: "Cayman Islands", value: "KY", available: true},
  {label: "Central African Republic", value: "CF", available: true},
  {label: "Chad", value: "TD", available: true},
  {label: "Chile", value: "CL", available: true},
  {label: "China", value: "CN", available: true},
  {label: "Christmas Island", value: "CX", available: true},
  {label: "Cocos (Keeling) Islands", value: "CC", available: true},
  {label: "Colombia", value: "CO", available: true},
  {label: "Comoros", value: "KM", available: true},
  {label: "Congo", value: "CG", available: true},
  {label: "Congo, The Democratic Republic of the", value: "CD", available: true},
  {label: "Cook Islands", value: "CK", available: true},
  {label: "Costa Rica", value: "CR", available: true},
  {label: "Cote Dvoire", value: "CI", available: true},
  {label: "Croatia", value: "HR", available: true},
  {label: "Cuba", value: "CU", available: true},
  {label: "Cyprus", value: "CY", available: true},
  {label: "Czech Republic", value: "CZ", available: true},
  {label: "Denmark", value: "DK", available: true},
  {label: "Djibouti", value: "DJ", available: true},
  {label: "Dominica", value: "DM", available: true},
  {label: "Dominican Republic", value: "DO", available: true},
  {label: "Ecuador", value: "EC", available: true},
  {label: "Egypt", value: "EG", available: true},
  {label: "El Salvador", value: "SV", available: true},
  {label: "Equatorial Guinea", value: "GQ", available: true},
  {label: "Eritrea", value: "ER", available: true},
  {label: "Estonia", value: "EE", available: true},
  {label: "Ethiopia", value: "ET", available: true},
  {label: "Falkland Islands (Malvinas)", value: "FK", available: true},
  {label: "Faroe Islands", value: "FO", available: true},
  {label: "Fiji", value: "FJ", available: true},
  {label: "Finland", value: "FI", available: true},
  {label: "France", value: "FR", available: true},
  {label: "French Guiana", value: "GF", available: true},
  {label: "French Polynesia", value: "PF", available: true},
  {label: "French Southern Territories", value: "TF", available: true},
  {label: "Gabon", value: "GA", available: true},
  {label: "Gambia", value: "GM", available: true},
  {label: "Georgia", value: "GE", available: true},
  {label: "Germany", value: "DE", available: true},
  {label: "Ghana", value: "GH", available: true},
  {label: "Gibraltar", value: "GI", available: true},
  {label: "Greece", value: "GR", available: true},
  {label: "Greenland", value: "GL", available: true},
  {label: "Grenada", value: "GD", available: true},
  {label: "Guadeloupe", value: "GP", available: true},
  {label: "Guam", value: "GU", available: true},
  {label: "Guatemala", value: "GT", available: true},
  {label: "Guernsey", value: "GG", available: true},
  {label: "Guinea", value: "GN", available: true},
  {label: "Guinea-Bissau", value: "GW", available: true},
  {label: "Guyana", value: "GY", available: true},
  {label: "Haiti", value: "HT", available: true},
  {label: "Heard Island and Mcdonald Islands", value: "HM", available: true},
  {label: "Holy See (Vatican City State)", value: "VA", available: true},
  {label: "Honduras", value: "HN", available: true},
  {label: "Hong Kong", value: "HK", available: true},
  {label: "Hungary", value: "HU", available: true},
  {label: "Iceland", value: "IS", available: true},
  {label: "India", value: "IN", available: true},
  {label: "Indonesia", value: "ID", available: true},
  {label: "Iran, Islamic Republic Of", value: "IR", available: true},
  {label: "Iraq", value: "IQ", available: true},
  {label: "Ireland", value: "IE", available: true},
  {label: "Isle of Man", value: "IM", available: true},
  {label: "Israel", value: "IL", available: true},
  {label: "Italy", value: "IT", available: true},
  {label: "Jamaica", value: "JM", available: true},
  {label: "Japan", value: "JP", available: true},
  {label: "Jersey", value: "JE", available: true},
  {label: "Jordan", value: "JO", available: true},
  {label: "Kazakhstan", value: "KZ", available: true},
  {label: "Kenya", value: "KE", available: true},
  {label: "Kiribati", value: "KI", available: true},
  {label: "Korea, Democratic PeopleS Republic of", value: "KP", available: true},
  {label: "Korea, Republic of", value: "KR", available: true},
  {label: "Kuwait", value: "KW", available: true},
  {label: "Kyrgyzstan", value: "KG", available: true},
  {label: "Lao PeopleS Democratic Republic", value: "LA", available: true},
  {label: "Latvia", value: "LV", available: true},
  {label: "Lebanon", value: "LB", available: true},
  {label: "Lesotho", value: "LS", available: true},
  {label: "Liberia", value: "LR", available: true},
  {label: "Libyan Arab Jamahiriya", value: "LY", available: true},
  {label: "Liechtenstein", value: "LI", available: true},
  {label: "Lithuania", value: "LT", available: true},
  {label: "Luxembourg", value: "LU", available: true},
  {label: "Macao", value: "MO", available: true},
  {label: "Macedonia, The Former Yugoslav Republic of", value: "MK", available: true},
  {label: "Madagascar", value: "MG", available: true},
  {label: "Malawi", value: "MW", available: true},
  {label: "Malaysia", value: "MY", available: true},
  {label: "Maldives", value: "MV", available: true},
  {label: "Mali", value: "ML", available: true},
  {label: "Malta", value: "MT", available: true},
  {label: "Marshall Islands", value: "MH", available: true},
  {label: "Martinique", value: "MQ", available: true},
  {label: "Mauritania", value: "MR", available: true},
  {label: "Mauritius", value: "MU", available: true},
  {label: "Mayotte", value: "YT", available: true},
  {label: "Mexico", value: "MX", available: true},
  {label: "Micronesia, Federated States of", value: "FM", available: true},
  {label: "Moldova, Republic of", value: "MD", available: true},
  {label: "Monaco", value: "MC", available: true},
  {label: "Mongolia", value: "MN", available: true},
  {label: "Montserrat", value: "MS", available: true},
  {label: "Morocco", value: "MA", available: true},
  {label: "Mozambique", value: "MZ", available: true},
  {label: "Myanmar", value: "MM", available: true},
  {label: "Namibia", value: "NA", available: true},
  {label: "Nauru", value: "NR", available: true},
  {label: "Nepal", value: "NP", available: true},
  {label: "Netherlands", value: "NL", available: true},
  {label: "Netherlands Antilles", value: "AN", available: true},
  {label: "New Caledonia", value: "NC", available: true},
  {label: "New Zealand", value: "NZ", available: true},
  {label: "Nicaragua", value: "NI", available: true},
  {label: "Niger", value: "NE", available: true},
  {label: "Nigeria", value: "NG", available: true},
  {label: "Niue", value: "NU", available: true},
  {label: "Norfolk Island", value: "NF", available: true},
  {label: "Northern Mariana Islands", value: "MP", available: true},
  {label: "Norway", value: "NO", available: true},
  {label: "Oman", value: "OM", available: true},
  {label: "Pakistan", value: "PK", available: true},
  {label: "Palau", value: "PW", available: true},
  {label: "Palestinian Territory, Occupied", value: "PS", available: true},
  {label: "Panama", value: "PA", available: true},
  {label: "Papua New Guinea", value: "PG", available: true},
  {label: "Paraguay", value: "PY", available: true},
  {label: "Peru", value: "PE", available: true},
  {label: "Philippines", value: "PH", available: true},
  {label: "Pitcairn", value: "PN", available: true},
  {label: "Poland", value: "PL", available: true},
  {label: "Portugal", value: "PT", available: true},
  {label: "Puerto Rico", value: "PR", available: true},
  {label: "Qatar", value: "QA", available: true},
  {label: "Reunion", value: "RE", available: true},
  {label: "Romania", value: "RO", available: true},
  {label: "Russian Federation", value: "RU", available: true},
  {label: "RWANDA", value: "RW", available: true},
  {label: "Saint Helena", value: "SH", available: true},
  {label: "Saint Kitts and Nevis", value: "KN", available: true},
  {label: "Saint Lucia", value: "LC", available: true},
  {label: "Saint Pierre and Miquelon", value: "PM", available: true},
  {label: "Saint Vincent and the Grenadines", value: "VC", available: true},
  {label: "Samoa", value: "WS", available: true},
  {label: "San Marino", value: "SM", available: true},
  {label: "Sao Tome and Principe", value: "ST", available: true},
  {label: "Saudi Arabia", value: "SA", available: true},
  {label: "Senegal", value: "SN", available: true},
  {label: "Serbia and Montenegro", value: "CS", available: true},
  {label: "Seychelles", value: "SC", available: true},
  {label: "Sierra Leone", value: "SL", available: true},
  {label: "Singapore", value: "SG", available: true},
  {label: "Slovakia", value: "SK", available: true},
  {label: "Slovenia", value: "SI", available: true},
  {label: "Solomon Islands", value: "SB", available: true},
  {label: "Somalia", value: "SO", available: true},
  {label: "South Africa", value: "ZA", available: true},
  {label: "South Georgia and the South Sandwich Islands", value: "GS", available: true},
  {label: "Spain", value: "ES", available: true},
  {label: "Sri Lanka", value: "LK", available: true},
  {label: "Sudan", value: "SD", available: true},
  {label: "Suriname", value: "SR", available: true},
  {label: "Svalbard and Jan Mayen", value: "SJ", available: true},
  {label: "Swaziland", value: "SZ", available: true},
  {label: "Sweden", value: "SE", available: true},
  {label: "Switzerland", value: "CH", available: true},
  {label: "Syrian Arab Republic", value: "SY", available: true},
  {label: "Taiwan, Province of China", value: "TW", available: true},
  {label: "Tajikistan", value: "TJ", available: true},
  {label: "Tanzania, United Republic of", value: "TZ", available: true},
  {label: "Thailand", value: "TH", available: true},
  {label: "Timor-Leste", value: "TL", available: true},
  {label: "Togo", value: "TG", available: true},
  {label: "Tokelau", value: "TK", available: true},
  {label: "Tonga", value: "TO", available: true},
  {label: "Trinidad and Tobago", value: "TT", available: true},
  {label: "Tunisia", value: "TN", available: true},
  {label: "Turkey", value: "TR", available: true},
  {label: "Turkmenistan", value: "TM", available: true},
  {label: "Turks and Caicos Islands", value: "TC", available: true},
  {label: "Tuvalu", value: "TV", available: true},
  {label: "Uganda", value: "UG", available: true},
  {label: "Ukraine", value: "UA", available: true},
  {label: "United Arab Emirates", value: "AE", available: true},
  {label: "United Kingdom", value: "GB", available: true},
  {label: "United States Minor Outlying Islands", value: "UM", available: true},
  {label: "Uruguay", value: "UY", available: true},
  {label: "Uzbekistan", value: "UZ", available: true},
  {label: "Vanuatu", value: "VU", available: true},
  {label: "Venezuela", value: "VE", available: true},
  {label: "Viet Nam", value: "VN", available: true},
  {label: "Virgin Islands, British", value: "VG", available: true},
  {label: "Virgin Islands, U.S.", value: "VI", available: true},
  {label: "Wallis and Futuna", value: "WF", available: true},
  {label: "Western Sahara", value: "EH", available: true},
  {label: "Yemen", value: "YE", available: true},
  {label: "Zambia", value: "ZM", available: true},
  {label: "Zimbabwe", value: "ZW", available: true},
];
